name: viziawork
description: "Viziawork - रोजी-रोटी का सीधा ठिकाना"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter_test
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # अगर आगे चलकर कस्टम फोंट या इमेज जोड़नी हों, तो यहाँ एसेट्स सेट किए जाएंगे
  # assets:
  #   - assets/images/
